// Save this as scripts/update-movies.js
// Run with: node scripts/update-movies.js
//
// This script clears and re-seeds movies_catalog and movie_news tables
// with fresh data from the March 30, 2026 deep research run.

require("dotenv").config({ path: ".env.local" });
const { createClient } = require("@supabase/supabase-js");

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

const movies = [
  // ═══ NOW PLAYING ═══
  { title: "Dhurandhar: The Revenge", language: "Hindi", genre: "Action, Spy Thriller", runtime: "3h 55m", release_date: "Mar 19, 2026", rating: "NR", imdb_rating: "8.6", synopsis: "Hamza Ali Mazari continues his undercover operation within Pakistan's criminal world, infiltrating Karachi's syndicates while avenging the 26/11 attacks. The explosive conclusion to the Dhurandhar duology starring Ranveer Singh.", poster_url: "https://m.media-amazon.com/images/M/MV5BNDAxNTU4MDEtMGJkYy00Y2MxLTllZTUtYTg2NDkzMGVjMjU5XkEyXkFqcGc@._V1_.jpg", trailer_youtube_id: "qPXjBGkjQYM", fandango_url: "https://www.fandango.com/dhurandhar-the-revenge-2026-244687/movie-overview", watch_url: null, platform: null, status: "now_playing" },
  { title: "Ustaad Bhagat Singh", language: "Telugu", genre: "Action, Comedy, Drama", runtime: "2h 34m", release_date: "Mar 19, 2026", rating: "NR", imdb_rating: "6.8", synopsis: "Inspired by his teacher who named him Bhagat Singh, a tribal boy grows up rooted in strong morals and takes on evil forces as a powerful police officer. Starring Pawan Kalyan.", poster_url: "https://assets.gadgets360cdn.com/pricee/assets/product/202503/Ustaad-Bhagat-Singh_1741588455.jpg", trailer_youtube_id: "aBNfH6gVWMA", fandango_url: "https://www.fandango.com/ustaad-bhagat-singh-2026-244706/movie-overview", watch_url: null, platform: null, status: "now_playing" },
  { title: "Aadu 3: One Last Ride – Part 1", language: "Malayalam", genre: "Fantasy, Action, Comedy", runtime: "2h 48m", release_date: "Mar 19, 2026", rating: "NR", imdb_rating: "7.8", synopsis: "The legendary Shaji Pappan and his mismatched gang stumble into their most absurd predicament yet in this fantasy comedy spanning three timelines connected by a mystical gem.", poster_url: "https://upload.wikimedia.org/wikipedia/en/4/4e/Aadu_3_poster.jpg", trailer_youtube_id: "MhVX9dGXBfg", fandango_url: "https://www.fandango.com/aadu-3-one-last-ride-part-1-2026-245098/movie-overview", watch_url: null, platform: null, status: "now_playing" },
  { title: "Band Melam", language: "Telugu", genre: "Romance, Drama, Musical", runtime: "2h 21m", release_date: "Mar 26, 2026", rating: "NR", imdb_rating: null, synopsis: "Childhood friends Giri and Raaji are torn apart by misfortune. She pursues education while he follows music with his village band, until their paths cross again.", poster_url: null, trailer_youtube_id: null, fandango_url: "https://www.fandango.com/movies-in-theaters", watch_url: null, platform: null, status: "now_playing" },
  { title: "Prathichaya", language: "Malayalam", genre: "Political Thriller, Drama", runtime: "2h 42m", release_date: "Mar 26, 2026", rating: "NR", imdb_rating: null, synopsis: "A tech entrepreneur and son of the Kerala Chief Minister finds his life upended when his father dies as part of a conspiracy. Stars Nivin Pauly.", poster_url: null, trailer_youtube_id: null, fandango_url: "https://www.fandango.com/prathichaya-2026-244959/movie-overview", watch_url: null, platform: null, status: "now_playing" },
  { title: "Happy Raj", language: "Tamil", genre: "Comedy, Romance, Family", runtime: "2h 36m", release_date: "Mar 27, 2026", rating: "NR", imdb_rating: null, synopsis: "A young man who has faced constant rejection due to his father's quirky reputation moves to the city and finds love, only to face a massive cultural clash when two families meet.", poster_url: null, trailer_youtube_id: null, fandango_url: "https://www.fandango.com/happy-raj-2026-244796/movie-overview", watch_url: null, platform: null, status: "now_playing" },
  { title: "Love Mocktail 3", language: "Kannada", genre: "Drama, Romance", runtime: "2h 20m", release_date: "Mar 19, 2026", rating: "NR", imdb_rating: null, synopsis: "Set years after Love Mocktail 2, Adi is now a single father to Nidhi. A custody battle and emotional challenges test his world in the final installment of the trilogy.", poster_url: null, trailer_youtube_id: null, fandango_url: "https://www.fandango.com/love-mocktail-3-2026-244797/movie-overview", watch_url: null, platform: null, status: "now_playing" },
  { title: "Suyodhana", language: "Telugu", genre: "Mystery, Drama, Thriller", runtime: "2h 10m", release_date: "Mar 27, 2026", rating: "NR", imdb_rating: null, synopsis: "A young Foley artist who has heard a mysterious voice named Suyodhana since childhood is accused of his father's murder. Stars Priyadarshi.", poster_url: null, trailer_youtube_id: null, fandango_url: "https://www.fandango.com/movies-in-theaters", watch_url: null, platform: null, status: "now_playing" },
  { title: "Youth", language: "Tamil", genre: "Comedy, Romance", runtime: "2h 22m", release_date: "Mar 19, 2026", rating: "NR", imdb_rating: null, synopsis: "15-year-old Praveen enters adolescence determined to find true love before school ends. Music by G. V. Prakash Kumar.", poster_url: null, trailer_youtube_id: "IxJBq0v2JNE", fandango_url: "https://www.fandango.com/youth-2026-244876/movie-overview", watch_url: null, platform: null, status: "now_playing" },
  { title: "Masthishka Maranam", language: "Malayalam", genre: "Sci-Fi, Comedy, Thriller", runtime: "2h 27m", release_date: "Mar 19, 2026", rating: "NR", imdb_rating: "7.7", synopsis: "In futuristic Neo-Kochi set in 2046, a grieving father enters a virtual-reality memory game to reconnect with his lost daughter, uncovering a dangerous conspiracy.", poster_url: null, trailer_youtube_id: null, fandango_url: "https://www.fandango.com/masthishka-maranam-2026-244659/movie-overview", watch_url: null, platform: null, status: "now_playing" },

  // ═══ NEW ON OTT ═══
  { title: "Dhurandhar", language: "Hindi", genre: "Action, Spy Thriller", runtime: "3h 34m", release_date: "Jan 30, 2026", rating: "A", imdb_rating: "8.3", synopsis: "An undercover Indian intelligence agent infiltrates Karachi's criminal syndicates in this epic spy thriller. The blockbuster that started it all — now streaming.", poster_url: "https://m.media-amazon.com/images/M/MV5BYTM4MjM3N2ItYThmMy00ZGIwLWFhMzMtZGE1YzNlZWNiMmMyXkEyXkFqcGc@._V1_.jpg", trailer_youtube_id: "yidGBQ5vL_s", fandango_url: null, watch_url: "https://www.netflix.com/title/81661375", platform: "Netflix", status: "ott" },
  { title: "Border 2", language: "Hindi", genre: "War, Action, Drama", runtime: "3h 21m", release_date: "Mar 20, 2026", rating: "NR", imdb_rating: "7.1", synopsis: "Set during the 1971 India-Pakistan War, this multi-front war drama follows soldiers across multiple battlefronts. Starring Sunny Deol, Varun Dhawan, Diljit Dosanjh.", poster_url: null, trailer_youtube_id: "OHedVzgun1c", fandango_url: null, watch_url: "https://www.netflix.com/title/81956873", platform: "Netflix", status: "ott" },
  { title: "Tu Meri Main Tera Main Tera Tu Meri", language: "Hindi", genre: "Romance, Comedy", runtime: "2h 25m", release_date: "Feb 19, 2026", rating: "U/A", imdb_rating: "4.0", synopsis: "Cynical LA-based wedding planner Ray (Kartik Aaryan) falls for traditional novelist Rumi (Ananya Panday) on a Croatia cruise, but clashing philosophies threaten their romance.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.primevideo.com/", platform: "Prime Video", status: "ott" },
  { title: "Ikkis", language: "Hindi", genre: "War, Biography, Drama", runtime: "2h 25m", release_date: "Feb 26, 2026", rating: "U/A 13+", imdb_rating: "6.1", synopsis: "Based on the true story of Lt. Arun Khetarpal, the youngest Param Vir Chakra awardee, who fought heroically during the 1971 Indo-Pak War's Battle of Basantar.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.primevideo.com/", platform: "Prime Video", status: "ott" },
  { title: "Subedaar", language: "Hindi", genre: "Action, Drama", runtime: "2h 22m", release_date: "Mar 5, 2026", rating: "U/A", imdb_rating: "6.1", synopsis: "Retired soldier Subedaar Arjun Maurya (Anil Kapoor) struggles to adapt to civilian life. When he confronts local corruption, he must summon his military combat skills.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.primevideo.com/", platform: "Prime Video", status: "ott" },
  { title: "Mardaani 3", language: "Hindi", genre: "Action, Crime, Thriller", runtime: "2h 10m", release_date: "Mar 27, 2026", rating: "U/A", imdb_rating: "7.5", synopsis: "Fearless cop Shivani Shivaji Roy (Rani Mukerji) returns to hunt down a ruthless child-trafficking network led by the villainous Amma.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.netflix.com/title/82023351", platform: "Netflix", status: "ott" },
  { title: "Jab Khuli Kitaab", language: "Hindi", genre: "Romantic Comedy-Drama", runtime: "2h 10m", release_date: "Mar 6, 2026", rating: "U/A", imdb_rating: "9.2", synopsis: "An elderly couple's 50-year marriage is shaken when wife Anusuya (Dimple Kapadia) confesses to an old affair, prompting husband Gopal (Pankaj Kapur) to file for divorce.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.zee5.com/", platform: "Zee5", status: "ott" },
  { title: "Accused", language: "Hindi", genre: "Drama, Mystery, Thriller", runtime: "1h 47m", release_date: "Feb 27, 2026", rating: "A", imdb_rating: "4.5", synopsis: "Dr. Geetika Sen (Konkona Sen Sharma), a celebrated gynaecologist in London, faces allegations of sexual misconduct that threaten her career and marriage.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.netflix.com/", platform: "Netflix", status: "ott" },
  { title: "O'Romeo", language: "Hindi", genre: "Action, Crime, Romantic Thriller", runtime: "2h 58m", release_date: "Mar 27, 2026", rating: "A", imdb_rating: "5.8", synopsis: "Set in 1990s Bombay, razor-wielding gangster Ustara (Shahid Kapoor) falls for Afshan (Triptii Dimri) who seeks help to avenge her husband's murder. Directed by Vishal Bhardwaj.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.primevideo.com/", platform: "Prime Video", status: "ott" },
  { title: "Tanvi The Great", language: "Hindi", genre: "Drama, Musical", runtime: "2h 39m", release_date: "Mar 3, 2026", rating: "U", imdb_rating: "6.9", synopsis: "A coming-of-age musical about Tanvi, a 21-year-old woman on the autism spectrum who resolves to join the Indian Army inspired by her father's dream.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.primevideo.com/", platform: "Prime Video", status: "ott" },
  { title: "Nari Nari Naduma Murari", language: "Telugu", genre: "Comedy, Romance", runtime: "2h 22m", release_date: "Feb 4, 2026", rating: "U/A", imdb_rating: "6.4", synopsis: "Architect Gautham (Sharwanand) supports his father's second marriage while navigating his own complicated love life and family opposition.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.primevideo.com/", platform: "Prime Video", status: "ott" },
  { title: "Bhartha Mahasayulaku Wignyapthi (BMW)", language: "Telugu", genre: "Comedy, Romance", runtime: "2h 30m", release_date: "Mar 13, 2026", rating: "U/A", imdb_rating: "7.4", synopsis: "Ram (Ravi Teja), a winemaker from Hyderabad, travels to Spain where his life gets complicated juggling between his wife and a woman from his past.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.zee5.com/", platform: "Zee5", status: "ott" },
  { title: "Funky", language: "Telugu", genre: "Comedy, Romance", runtime: "2h 08m", release_date: "Mar 13, 2026", rating: "U/A", imdb_rating: "4.1", synopsis: "Komal (Vishwak Sen), a struggling filmmaker, tries to complete his debut film. When the producer's daughter steps in, romance blossoms amid creative chaos.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.netflix.com/", platform: "Netflix", status: "ott" },
  { title: "Couple Friendly", language: "Telugu", genre: "Romance, Comedy", runtime: "2h 10m", release_date: "Mar 13, 2026", rating: "U/A", imdb_rating: null, synopsis: "A youthful romantic entertainer starring Santosh Sobhan and Manasa Varanasi exploring modern love and relationships.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.primevideo.com/", platform: "Prime Video", status: "ott" },
  { title: "With Love", language: "Tamil", genre: "Romantic Comedy, Drama", runtime: "2h 21m", release_date: "Mar 6, 2026", rating: "U/A", imdb_rating: "7.6", synopsis: "Old schoolmates meet on a blind date and resolve to reconnect with past flames while growing closer to each other. Produced by Soundarya Rajinikanth.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.netflix.com/", platform: "Netflix", status: "ott" },
  { title: "Pookie", language: "Tamil", genre: "Romance, Comedy, Drama", runtime: "2h 09m", release_date: "Mar 13, 2026", rating: "U/A", imdb_rating: "7.3", synopsis: "A young couple's six-year relationship collapses after a public breakup. A film exploring the complexities of modern Gen Z love.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.zee5.com/", platform: "Zee5", status: "ott" },
  { title: "Thaai Kizhavi", language: "Tamil", genre: "Comedy, Drama", runtime: "2h 22m", release_date: "Mar 26, 2026", rating: "U", imdb_rating: "8.5", synopsis: "An aged village moneylender falls ill, and her three estranged sons rush home expecting inheritance, only to discover hidden treasure — forcing them to keep her alive. The biggest Tamil hit of early 2026.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.jiohotstar.com/", platform: "Hotstar", status: "ott" },
  { title: "Thalaivar Thambi Thalaimaiyil", language: "Tamil", genre: "Comedy, Drama", runtime: "2h 10m", release_date: "Feb 12, 2026", rating: "U/A", imdb_rating: "7.0", synopsis: "A comedic family drama exploring sibling dynamics and leadership within a household. Stars Jiiva.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.netflix.com/", platform: "Netflix", status: "ott" },
  { title: "Prakambanam", language: "Malayalam", genre: "Horror, Comedy", runtime: "2h 05m", release_date: "Mar 14, 2026", rating: "U/A", imdb_rating: "6.0", synopsis: "Three college friends' life turns chaotic when one becomes possessed by his grandmother's spirit. The most profitable Malayalam film of 2026.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.zee5.com/", platform: "Zee5", status: "ott" },
  { title: "Chatha Pacha: The Ring of Rowdies", language: "Malayalam", genre: "Action, Comedy", runtime: "2h 10m", release_date: "Feb 19, 2026", rating: "U/A", imdb_rating: null, synopsis: "Three brothers establish a locally organised, WWE-style wrestling promotion in Fort Kochi. A high-energy action-comedy.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.netflix.com/", platform: "Netflix", status: "ott" },
  { title: "Theertharoopa Thandeyavarige", language: "Kannada", genre: "Family Drama", runtime: "2h 26m", release_date: "Feb 20, 2026", rating: "U/A", imdb_rating: "7.2", synopsis: "A popular travel vlogger discovers unsettling truths about his family while searching for his estranged father.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.primevideo.com/", platform: "Prime Video", status: "ott" },
  { title: "Hot Spot 2 Much", language: "Tamil", genre: "Social Drama", runtime: "2h 00m", release_date: "Feb 20, 2026", rating: "A", imdb_rating: null, synopsis: "A hyperlink narrative exploring contemporary social themes including toxic fan culture, same-sex marriage, and personal freedoms.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.primevideo.com/", platform: "Prime Video", status: "ott" },
  { title: "Kis Kisko Pyaar Karoon 2", language: "Hindi", genre: "Comedy", runtime: "2h 10m", release_date: "Feb 6, 2026", rating: "U/A", imdb_rating: null, synopsis: "Kapil Sharma returns as restaurant owner Mohan whose life turns chaotic after he accidentally marries three women from different faiths.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: "https://www.jiohotstar.com/", platform: "Hotstar", status: "ott" },

  // ═══ COMING SOON ═══
  { title: "Bhooth Bangla", language: "Hindi", genre: "Horror, Comedy", runtime: null, release_date: "Apr 17, 2026", rating: null, imdb_rating: null, synopsis: "A horror-comedy marking the reunion of Akshay Kumar and director Priyadarshan after 14 years. Haunted house antics and classic comedy.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: null, platform: null, status: "coming_soon" },
  { title: "Dacoit: A Love Story", language: "Telugu", genre: "Action, Romance, Thriller", runtime: null, release_date: "Apr 10, 2026", rating: null, imdb_rating: null, synopsis: "An angry convict escapes prison to seek revenge against his ex-girlfriend who betrayed him. Stars Adivi Sesh and Mrunal Thakur.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: null, platform: null, status: "coming_soon" },
  { title: "Pallichattambi", language: "Malayalam", genre: "Action, Thriller", runtime: null, release_date: "Apr 10, 2026", rating: null, imdb_rating: null, synopsis: "A Malayalam action-thriller starring Tovino Thomas, directed by Dijo Jose Antony (Jana Gana Mana).", poster_url: null, trailer_youtube_id: "cicdTszL548", fandango_url: null, watch_url: null, platform: null, status: "coming_soon" },
  { title: "Swayambhu", language: "Telugu", genre: "Action, Fantasy", runtime: null, release_date: "Apr 10, 2026", rating: null, imdb_rating: null, synopsis: "A highly anticipated Telugu fantasy-action film featuring Nikhil Siddhartha in a mythological avatar.", poster_url: null, trailer_youtube_id: "1J1FAqavUwA", fandango_url: null, watch_url: null, platform: null, status: "coming_soon" },
  { title: "Peddi", language: "Telugu", genre: "Action, Drama, Sport", runtime: null, release_date: "Apr 30, 2026", rating: null, imdb_rating: null, synopsis: "Set in 1980s rural Andhra Pradesh, a spirited villager unites his community through sports. Stars Ram Charan with music by A.R. Rahman.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: null, platform: null, status: "coming_soon" },
  { title: "Ginny Weds Sunny 2", language: "Hindi", genre: "Romance, Comedy", runtime: null, release_date: "Apr 24, 2026", rating: null, imdb_rating: null, synopsis: "Sequel to the popular romantic comedy continuing the fun romantic saga with new twists.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: null, platform: null, status: "coming_soon" },
  { title: "Toxic: A Fairy Tale for Grown-ups", language: "Kannada", genre: "Action, Crime, Thriller", runtime: null, release_date: "Jun 4, 2026", rating: null, imdb_rating: null, synopsis: "A dark fairy tale set in Goa where a powerful drug cartel pulls the strings. Yash's first project after KGF, co-starring Nayanthara and Kiara Advani.", poster_url: "https://upload.wikimedia.org/wikipedia/en/4/42/Toxic_film_poster.jpg", trailer_youtube_id: null, fandango_url: null, watch_url: null, platform: null, status: "coming_soon" },
  { title: "Pati Patni Aur Woh Do", language: "Hindi", genre: "Comedy, Romance", runtime: null, release_date: "May 15, 2026", rating: null, imdb_rating: null, synopsis: "Spiritual sequel exploring modern marriage chaos. Stars Ayushmann Khurrana, Sara Ali Khan, Wamiqa Gabbi, and Pankaj Tripathi.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: null, platform: null, status: "coming_soon" },
  { title: "Cocktail 2", language: "Hindi", genre: "Romance, Comedy, Drama", runtime: null, release_date: "Jun 19, 2026", rating: null, imdb_rating: null, synopsis: "Spiritual sequel to the 2012 hit exploring modern relationships. Stars Shahid Kapoor, Rashmika Mandanna, and Kriti Sanon.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: null, platform: null, status: "coming_soon" },
  { title: "Kattalan", language: "Malayalam", genre: "Action, Thriller", runtime: null, release_date: "May 14, 2026", rating: null, imdb_rating: null, synopsis: "A high-octane pan-Indian action thriller. Stars Antony Varghese with music by B. Ajaneesh Loknath.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: null, platform: null, status: "coming_soon" },
  { title: "Hai Jawani Toh Ishq Hona Hai", language: "Hindi", genre: "Romantic Comedy", runtime: null, release_date: "Jun 12, 2026", rating: null, imdb_rating: null, synopsis: "A classic David Dhawan-style romantic comedy starring Varun Dhawan, Pooja Hegde, and Mrunal Thakur.", poster_url: null, trailer_youtube_id: null, fandango_url: null, watch_url: null, platform: null, status: "coming_soon" },
];

const news = [
  { headline: "Dhurandhar: The Revenge shatters every Bollywood record — crosses ₹1,250 crore worldwide in 10 days", source: "Deadline", url: "https://deadline.com/2026/03/box-office-dhurandhar-the-revenge-1236763168/", image_url: "https://m.media-amazon.com/images/M/MV5BNDAxNTU4MDEtMGJkYy00Y2MxLTllZTUtYTg2NDkzMGVjMjU5XkEyXkFqcGc@._V1_.jpg", published_date: "2026-03-27" },
  { headline: "Yash's Toxic postponed to June 4 amid Middle East tensions, clears path for Dhurandhar 2", source: "Variety", url: "https://variety.com/2026/film/news/yash-toxic-june-release-middle-east-uncertainty-dhurandar-1236678996/", image_url: "https://upload.wikimedia.org/wikipedia/en/4/42/Toxic_film_poster.jpg", published_date: "2026-03-04" },
  { headline: "Thaai Kizhavi emerges as Tamil cinema's surprise blockbuster with 500% ROI on ₹9Cr budget", source: "Koimoi", url: "https://www.koimoi.com/box-office/thaai-kizhavi-box-office-becomes-first-tamil-film-of-2026-to-deliver-50-crore-profit/", image_url: null, published_date: "2026-03-28" },
  { headline: "Aadu 3 revives Malayalam box office — crosses ₹100 crore to become highest grosser of 2026", source: "Onmanorama", url: "https://www.onmanorama.com/entertainment/entertainment-news/2026/03/23/aadu-3-movie-malayalam-cinema-hit-2026-jayasurya-box-office.html", image_url: "https://upload.wikimedia.org/wikipedia/en/4/4e/Aadu_3_poster.jpg", published_date: "2026-03-23" },
  { headline: "Pawan Kalyan's Ustaad Bhagat Singh declared box office disappointment — ₹94Cr vs ₹150Cr budget", source: "India TV News", url: "https://www.indiatvnews.com/entertainment/regional-cinema/ustaad-bhagat-singh-box-office-report-26-march-2026", image_url: "https://assets.gadgets360cdn.com/pricee/assets/product/202503/Ustaad-Bhagat-Singh_1741588455.jpg", published_date: "2026-03-26" },
  { headline: "Border 2 debuts on Netflix March 20 after ₹464 crore theatrical run — Border 3 confirmed", source: "Filmibeat", url: "https://www.filmibeat.com/photo-gallery/border-2-ott-release-date-sunny-deols-war-blockbuster-arrives-on-netflix-106022.html", image_url: null, published_date: "2026-03-13" },
  { headline: "Vijay Deverakonda and Rashmika Mandanna host star-studded VIROSH wedding reception in Hyderabad", source: "India TV News", url: "https://www.indiatvnews.com/entertainment/regional-cinema/rashmika-mandanna-vijay-deverakonda-wedding-reception-live-updates-hyderabad", image_url: null, published_date: "2026-03-04" },
  { headline: "Sanjay Leela Bhansali's Love and War pushed out of 2026 — eyes late 2026 or 2027 release", source: "Hollywood Reporter India", url: "https://www.hollywoodreporterindia.com/features/insight/sanjay-leela-bhansalis-love-and-war-pushed-to-2027", image_url: null, published_date: "2026-03-01" },
  { headline: "Dhurandhar re-released on 1,000+ screens ahead of sequel in unprecedented Indian cinema first", source: "Sacnilk", url: "https://www.sacnilk.com/news/March_2026_Box_Office_Clash", image_url: null, published_date: "2026-03-13" },
  { headline: "Pinkvilla Screen and Style Icons Awards 2026 honors Aditya Dhar, Kriti Sanon, and Yami Gautam", source: "Pinkvilla", url: "https://www.pinkvilla.com/cinema/pinkvilla-screen-style-icons-awards-2026-complete-list-of-winners", image_url: null, published_date: "2026-03-25" },
];

async function run() {
  console.log("🎬 Starting movies data update...\n");

  // Clear existing data
  console.log("Clearing movies_catalog...");
  const { error: e1 } = await supabase.from("movies_catalog").delete().neq("id", 0);
  if (e1) console.error("Error clearing movies_catalog:", e1.message);
  else console.log("✅ movies_catalog cleared");

  console.log("Clearing movie_news...");
  const { error: e2 } = await supabase.from("movie_news").delete().neq("id", 0);
  if (e2) console.error("Error clearing movie_news:", e2.message);
  else console.log("✅ movie_news cleared");

  // Insert movies in batches of 10
  console.log(`\nInserting ${movies.length} movies...`);
  for (let i = 0; i < movies.length; i += 10) {
    const batch = movies.slice(i, i + 10);
    const { error } = await supabase.from("movies_catalog").insert(batch);
    if (error) {
      console.error(`Error inserting movies batch ${i / 10 + 1}:`, error.message);
    } else {
      console.log(`✅ Batch ${i / 10 + 1}: ${batch.length} movies inserted`);
    }
  }

  // Insert news
  console.log(`\nInserting ${news.length} news stories...`);
  const { error: e3 } = await supabase.from("movie_news").insert(news);
  if (e3) console.error("Error inserting news:", e3.message);
  else console.log("✅ All news inserted");

  // Summary
  const { count: mc } = await supabase.from("movies_catalog").select("*", { count: "exact", head: true });
  const { count: nc } = await supabase.from("movie_news").select("*", { count: "exact", head: true });
  console.log(`\n🎬 Done! ${mc} movies, ${nc} news stories in database.`);
  console.log(`   Now Playing: ${movies.filter(m => m.status === "now_playing").length}`);
  console.log(`   New on OTT: ${movies.filter(m => m.status === "ott").length}`);
  console.log(`   Coming Soon: ${movies.filter(m => m.status === "coming_soon").length}`);
}

run().catch(console.error);
